[common]
port = ":8086"
[db]
driver  = "mysql"
connstr = "root:tester@tcp(127.0.0.1:3306)/copyright?charset=utf8"
[eth]
connstr = "http://localhost:8545"
keydir = "../../data/keystore"
fundation = "0x839ce39c7942e33280daede63598c26170bc0d30"
hotelAddr = "0x738e058e45da33239c5956553eaf3a1a5e7e3191"
fundationPWD = "eilinge"